name: Lint and Test

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install .[test]
      - run: pytest --cov=classicdata --cov-report=xml
      - run: pylint classicdata
      - name: codecov
        uses: codecov/codecov-action@v2

